language: php

notifications:
  email:
    on_success: never
    on_failure: change

services:
  - mysql

php:
  - 5.6
  - 5.5

env:
  - WP_VERSION=latest WP_MULTISITE=0

install:
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - mysql -e 'create database wptestloader;'
  # configure apache virtual hosts
  - echo "$(curl -fsSL https://gist.githubusercontent.com/cyberhiker/e273a56610c80f2b970f8b317880f095/raw/be0139a922ed2ba494e099daf43e67b8b75f203e/apacheTester.conf)" | sed -e "s,PATH,`pwd`/www,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - echo "127.0.0.1 wptest.localhost" | sudo tee -a /etc/hosts
  - sudo service apache2 restart
  - sudo apt-get install git
  - wget http://codeception.com/codecept.phar
  - sudo curl -LsS http://codeception.com/codecept.phar -o /usr/local/bin/codecept
  - sudo chmod a+x /usr/local/bin/codecept
  - codecept
  - composer require lucatume/wp-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - java -jar selenium-server-standalone-2.42.2.jar -port 4444 -Djava.security.egd=file:///dev/urandom switch > /dev/null &
  - sleep 10
  - bash tests/bin/install.sh wptest root '' localhost $WP_VERSION

script:
  - ./vendor/bin/wpcept run --steps --debug

after_failure:
  - bash tests/bin/upload.sh
