<?php
class PlatformPress_Options_Fields
{
	public function __construct() {
		$this->add_option_groups();
	}

	public function add_option_groups() {

		$settings = ap_opt();

		// Register general settings
		ap_register_option_group('general', __( 'General', 'platformpress' ) , array(
			array(
				'name' 			=> 'platformpress_opt[base_page]',
				'label' 		=> __( 'Base page', 'platformpress' ),
				'desc' 			=> __( 'Select page for displaying platformpress.', 'platformpress' ),
				'type' 			=> 'page_select',
				'value' 		=> @$settings['base_page'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[question_help_page]',
				'label' => __( 'Question Help page', 'platformpress' ),
				'desc' => __( 'Direction for commenting a question.', 'platformpress' ),
				'type' => 'page_select',
				'value' => @$settings['question_help_page'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[answer_help_page]',
				'label' => __( 'Answer Help page', 'platformpress' ),
				'desc' => __( 'Direction for answring a question.', 'platformpress' ),
				'type' => 'page_select',
				'value' => @$settings['answer_help_page'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[author_credits]',
				'label' => __( 'Hide author credits', 'platformpress' ),
				'desc' => __( 'Hide link to PlatformPress project site.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => @$settings['author_credits'],
				'order' => '1',
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[allow_private_posts]',
				'label' => __( 'Allow private posts', 'platformpress' ),
				'desc' => __( 'Allow users to create private question and answer.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => @$settings['allow_private_posts'],
				'show_desc_tip' => false,
			),

			array(
				'name' => 'platformpress_opt[db_cleanup]',
				'label' => __( 'Clean DB', 'platformpress' ),
				'desc' => __( 'check this to remove all platformpress data including posts on deactivating plugin.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => @$settings['db_cleanup'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[question_permalink_follow]',
				'label' => __( 'Base page slug before question permalink', 'platformpress' ),
				'desc' => __( 'i.e. '.home_url( '/BASE_PAGE/question/QUESTION_TITLE' ), 'platformpress' ),
				'type' => 'checkbox',
				'value' => @$settings['question_permalink_follow'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[base_before_user_perma]',
				'label' => __( 'Base page slug before user page permalink', 'platformpress' ),
				'desc' => __( 'i.e. '.home_url( '/BASE_PAGE/user/USER_NAME' ), 'platformpress' ),
				'type' => 'checkbox',
				'value' => @$settings['base_before_user_perma'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[disable_hover_card]',
				'label' => __( 'Disable hover card', 'platformpress' ),
				'desc' => __( 'Dont show user hover card on mouseover.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => @$settings['disable_hover_card'],
				'show_desc_tip' => false,
			),

		));

		// Register layout settings
		ap_register_option_group('layout', __( 'Layout', 'platformpress' ) , array(
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<span class="ap-form-separator">' . __( 'Avatar', 'platformpress' ) . '</span>',
			) ,
			array(
				'name' => 'platformpress_opt[load_assets_in_platformpress_only]',
				'label' => __( 'Load assets in PlatformPress page only?', 'platformpress' ),
				'desc' => __( 'Check this to load PlatformPress JS and CSS on the PlatformPress page only. Be careful, this might break layout.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['load_assets_in_platformpress_only'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[avatar_size_list]',
				'label' => __( 'List avatar size', 'platformpress' ),
				'desc' => __( 'User avatar size for questions list.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['avatar_size_list'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[avatar_size_qquestion]',
				'label' => __( 'Question avatar size', 'platformpress' ),
				'desc' => __( 'User avatar size for question.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['avatar_size_qquestion'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[avatar_size_qanswer]',
				'label' => __( 'Answer avatar size', 'platformpress' ),
				'desc' => __( 'User avatar size for answer.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['avatar_size_qanswer'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[avatar_size_qanswer]',
				'label' => __( 'Answer avatar size', 'platformpress' ),
				'desc' => __( 'User avatar size for answer.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['avatar_size_qanswer'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[avatar_size_qcomment]',
				'label' => __( 'Comment avatar size', 'platformpress' ),
				'desc' => __( 'User avatar size for comments.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['avatar_size_qcomment'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<span class="ap-form-separator">' . __( 'Items to show per page', 'platformpress' ) . '</span>',
			) ,
			array(
				'name' => 'platformpress_opt[question_per_page]',
				'label' => __( 'Questions per page', 'platformpress' ),
				'desc' => __( 'Questions to show per page.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['question_per_page'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[answers_per_page]',
				'label' => __( 'Answers per page', 'platformpress' ),
				'desc' => __( 'Answers to show per page.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['answers_per_page'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[users_per_page]',
				'label' => __( 'Users per page', 'platformpress' ),
				'desc' => __( 'Users to show per page.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['users_per_page'],
			) ,
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<span class="ap-form-separator">' . __( 'Sorting', 'platformpress' ) . '</span>',
			) ,
			array(
				'name' => 'platformpress_opt[answers_sort]',
				'label' => __( 'Default answer sort', 'platformpress' ),
				'desc' => __( 'Sort answers by default.', 'platformpress' ),
				'type' => 'select',
				'options' => array(
					'voted' => __( 'Voted', 'platformpress' ),
					'active' => __( 'Active', 'platformpress' ),
					'newest' => __( 'Newest', 'platformpress' ),
					'oldest' => __( 'Oldest', 'platformpress' ),
				),
				'value' => $settings['answers_sort'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<span class="ap-form-separator">' . __( 'Toggle', 'platformpress' ) . '</span>',
			) ,
			array(
				'name' => 'platformpress_opt[show_question_sidebar]',
				'label' => __( 'Show question sidebar', 'platformpress' ),
				'desc' => __( 'Subscribe and Stats widgets will be shown on question page.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['show_question_sidebar'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[notification_sidebar]',
				'label' => __( 'Show notification sidebar', 'platformpress' ),
				'desc' => __( 'Show dropdown notification as sidebar', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['notification_sidebar'],
				'show_desc_tip' => false,
			),
		));

		// Register pages settings
		ap_register_option_group('pages', __( 'Pages', 'platformpress' ) , array(
			array(
				'name' => '__sep',
				'type' => 'custom',
				'order' => 5,
				'html' => '<span class="ap-form-separator">' . __( 'Page slug', 'platformpress' ) . '</span>',
			),
			array(
				'name' => 'platformpress_opt[comment_page_slug]',
				'label' => __( 'comment page slug', 'platformpress' ),
				'desc' => __( 'Enter slug for comment page.', 'platformpress' ),
				'type' => 'text',
				'value' => @$settings['comment_page_slug'],
				'show_desc_tip' => false,
				'order' => 5,
			),
			array(
				'name' => 'platformpress_opt[question_page_slug]',
				'label' => __( 'Question page slug', 'platformpress' ),
				'desc' => __( 'Enter slug for question page.', 'platformpress' ),
				'type' => 'text',
				'value' => @$settings['question_page_slug'],
				'show_desc_tip' => false,
				'order' => 5,
			),
			array(
				'name' => 'platformpress_opt[users_page_slug]',
				'label' => __( 'Users page slug', 'platformpress' ),
				'desc' => __( 'Enter slug for users page.', 'platformpress' ),
				'type' => 'text',
				'value' => @$settings['users_page_slug'],
				'show_desc_tip' => false,
				'order' => 5,
			),
			array(
				'name' => 'platformpress_opt[user_page_slug]',
				'label' => __( 'User page slug', 'platformpress' ),
				'desc' => __( 'Enter slug for user page, make sure no page or post exists with same slug.', 'platformpress' ),
				'type' => 'text',
				'value' => @$settings['user_page_slug'],
				'show_desc_tip' => false,
				'order' => 5,
			),
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<span class="ap-form-separator">' . __( 'Page titles', 'platformpress' ) . '</span>',
			) ,
			array(
				'name' => 'platformpress_opt[show_title_in_question]',
				'label' => __( 'Show question title', 'platformpress' ),
				'desc' => __( 'Show question title in single question page.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['show_title_in_question'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[show_solved_prefix]',
				'label' => __( 'Show solved prefix', 'platformpress' ),
				'desc' => __( 'If an answer is selected for question then [solved] prefix will be added in title.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['show_solved_prefix'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[base_page_title]',
				'label' => __( 'Base page title', 'platformpress' ),
				'desc' => __( 'Main questions list page title', 'platformpress' ),
				'type' => 'text',
				'value' => $settings['base_page_title'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[comment_page_title]',
				'label' => __( 'comment page title', 'platformpress' ),
				'desc' => __( 'Title of the comment page', 'platformpress' ),
				'type' => 'text',
				'value' => $settings['comment_page_title'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[users_page_title]',
				'label' => __( 'Users page title', 'platformpress' ),
				'desc' => __( 'Title of the users page', 'platformpress' ),
				'type' => 'text',
				'value' => $settings['users_page_title'],
				'show_desc_tip' => false,
			),array(
				'name' => 'platformpress_opt[search_page_title]',
				'label' => __( 'Search page title', 'platformpress' ),
				'desc' => __( 'Title of the search page', 'platformpress' ),
				'type' => 'text',
				'value' => $settings['search_page_title'],
				'show_desc_tip' => false,
			)
		));

		// Register question settings
		ap_register_option_group('question', __( 'Question & Answer', 'platformpress' ) , array(
			array(
				'name' => 'platformpress_opt[default_date_format]',
				'label' => __( 'Show default date format', 'platformpress' ),
				'desc' => __( 'Instead of showing time passed i.e. 1 Hour ago, show default format date.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['default_date_format'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<span class="ap-form-separator">' . __( 'Question', 'platformpress' ) . '</span>',
			) ,
			array(
				'name' => 'platformpress_opt[keep_stop_words]',
				'label' => __( 'Keep stop words in question slug', 'platformpress' ),
				'desc' => __( 'PlatformPress will not strip stop words in question slug.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['keep_stop_words'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[minimum_qtitle_length]',
				'label' => __( 'Minimum title length', 'platformpress' ),
				'desc' => __( 'Set minimum letters for a question title.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['minimum_qtitle_length'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[minimum_question_length]',
				'label' => __( 'Minimum question content', 'platformpress' ),
				'desc' => __( 'Set minimum letters for a question contents.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['minimum_question_length'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[question_text_editor]',
				'label' => __( 'Use text editor ?', 'platformpress' ),
				'desc' => __( 'Text editor as default.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['question_text_editor'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[disable_comments_on_question]',
				'label' => __( 'Disable comments', 'platformpress' ),
				'desc' => __( 'Disable comments on questions.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['disable_comments_on_question'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[disable_voting_on_question]',
				'label' => __( 'Disable voting', 'platformpress' ),
				'desc' => __( 'Disable voting on questions.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['disable_voting_on_question'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[disable_down_vote_on_question]',
				'label' => __( 'Disable down voting', 'platformpress' ),
				'desc' => __( 'Disable down voting on questions.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['disable_down_vote_on_question'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[close_selected]',
				'label' => __( 'Close question after selecting answer', 'platformpress' ),
				'desc' => __( 'If enabled this will prevent user to submit answer on solved question.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['close_selected'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<br /><span class="ap-form-separator">' . __( 'Answer', 'platformpress' ) . '</span>',
			) ,
			array(
				'name' => 'platformpress_opt[multiple_answers]',
				'label' => __( 'Multiple Answers', 'platformpress' ),
				'desc' => __( 'Allow an user to submit multiple answers on a single question.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['multiple_answers'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[minimum_ans_length]',
				'label' => __( 'Minimum question content', 'platformpress' ),
				'desc' => __( 'Set minimum letters for a answer contents.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['minimum_ans_length'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[answer_text_editor]',
				'label' => __( 'Use text editor ?', 'platformpress' ),
				'desc' => __( 'Text editor as default.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['answer_text_editor'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[disable_comments_on_answer]',
				'label' => __( 'Disable comments', 'platformpress' ),
				'desc' => __( 'Disable comments on answer.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['disable_comments_on_answer'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[disable_voting_on_answer]',
				'label' => __( 'Disable voting', 'platformpress' ),
				'desc' => __( 'Disable voting on answers.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['disable_voting_on_answer'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[disable_down_vote_on_answer]',
				'label' => __( 'Disable down voting', 'platformpress' ),
				'desc' => __( 'Disable down voting on answers.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['disable_down_vote_on_answer'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[disable_answer_nav]',
				'label' => __( 'Disable navigation', 'platformpress' ),
				'desc' => __( 'Disable answer navigation.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['disable_answer_nav'],
				'show_desc_tip' => false,
			) ,
		));

		// register user settings
		ap_register_option_group('users', __( 'Users', 'platformpress' ) , array(
			array(
				'name' => 'platformpress_opt[user_profile]',
				'label' => __( 'User profile', 'platformpress' ),
				'desc' => __( 'Select which user profile you\'d like to use.', 'platformpress' ),
				'type' => 'select',
				'value' => $settings['user_profile'],
				'show_desc_tip' => false,
				'options' => array( 'platformpress' => 'PlatformPress', 'buddypress' => 'BuddyPress', 'userpro' => 'User Pro' ),
			) ,
			array(
				'name' => 'platformpress_opt[enable_users_directory]',
				'label' => __( 'Show users directory', 'platformpress' ),
				'desc' => __( 'When enabled public can see directory of users.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['enable_users_directory'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<span class="ap-form-separator">' . __( 'Features', 'platformpress' ) . '</span>',
			) ,
			array(
				'name' => 'platformpress_opt[disable_reputation]',
				'label' => __( 'Disable reputation', 'platformpress' ),
				'desc' => __( 'Disable reputation for user', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['disable_reputation'],
				'show_desc_tip' => false,
			) ,

			array(
				'name' => 'platformpress_opt[users_page_avatar_size]',
				'label' => __( 'Users page avatar size', 'platformpress' ),
				'desc' => __( 'Set user avatar size for users page item.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['users_page_avatar_size'],
				'show_desc_tip' => false,
			) ,

			array(
				'name' => 'platformpress_opt[cover_width]',
				'label' => __( 'Cover width', 'platformpress' ),
				'desc' => __( 'Set width of user cover photo.', 'platformpress' ),
				'type' => 'number',
				'value' => @$settings['cover_width'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[cover_height]',
				'label' => __( 'Cover height', 'platformpress' ),
				'desc' => __( 'Set height of user cover photo.', 'platformpress' ),
				'type' => 'number',
				'value' => @$settings['cover_height'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[cover_width_small]',
				'label' => __( 'Cover thumb width', 'platformpress' ),
				'desc' => __( 'Set width of user cover photo thumbnail.', 'platformpress' ),
				'type' => 'number',
				'value' => @$settings['cover_width_small'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[cover_height_small]',
				'label' => __( 'Small cover height', 'platformpress' ),
				'desc' => __( 'Set height of user cover photo thumbnail.', 'platformpress' ),
				'type' => 'number',
				'value' => @$settings['cover_height_small'],
				'show_desc_tip' => false,
			) ,
		));

		// register permission settings
		ap_register_option_group('permission', __( 'Permission', 'platformpress' ) , array(
			array(
				'name' => 'platformpress_opt[only_logged_in]',
				'label' => __( 'Only logged in can see questions, answer and comments?', 'platformpress' ),
				'desc' => __( 'Require user to login to see PlatformPress contents?.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['only_logged_in'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[multiple_answers]',
				'label' => __( 'Multiple answers', 'platformpress' ),
				'desc' => __( 'Allow user to submit multiple answer per question.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['multiple_answers'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[disallow_op_to_answer]',
				'label' => __( 'commenter can answer', 'platformpress' ),
				'desc' => __( 'Allow commenter to answer his own question.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['disallow_op_to_answer'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[allow_anonymous]',
				'label' => __( 'Allow anonymous', 'platformpress' ),
				'desc' => __( 'Non-loggedin user can post questions and answers.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['allow_anonymous'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[only_admin_can_answer]',
				'label' => __( 'Only admin can answer', 'platformpress' ),
				'desc' => __( 'Only allow admin to answer question.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['only_admin_can_answer'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[logged_in_can_see_ans]',
				'label' => __( 'Only logged in can see answers', 'platformpress' ),
				'desc' => __( 'non-loggedin user cannot see answers.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['logged_in_can_see_ans'],
				'show_desc_tip' => false,
			),
			
			array(
				'name' => 'platformpress_opt[logged_in_can_see_comment]',
				'label' => __( 'Only logged in can see comment', 'platformpress' ),
				'desc' => __( 'non-loggedin user cannot see comments.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['logged_in_can_see_comment'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[disable_delete_after]',
				'label' => __( 'Lock delete action', 'platformpress' ),
				'desc' => __( 'Lock comment or post after a period so that user cannot delete it. Set the time in epoch i.e. 86400 = 1 day.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['disable_delete_after'],
				'show_desc_tip' => false,
			),
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<span class="ap-form-separator">' . __( 'Upload', 'platformpress' ) . '</span>',
			),
			array(
				'name' => 'platformpress_opt[allow_upload_image]',
				'label' => __( 'Allow image upload', 'platformpress' ),
				'desc' => __( 'Allow logged-in users to upload image.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['allow_upload_image'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[image_per_post]',
				'label' => __( 'Max images per post', 'platformpress' ),
				'desc' => __( 'Set how many images user can upload for each post.', 'platformpress' ),
				'type' => 'number',
				'value' => $settings['image_per_post'],
				'show_desc_tip' => false,
			),
			array(
				'name' => 'platformpress_opt[max_upload_size]',
				'label' => __( 'Max upload size', 'platformpress' ),
				'desc' => __( 'Set maximum upload size.', 'platformpress' ),
				'type' => 'text',
				'value' => $settings['max_upload_size'],
				'show_desc_tip' => false,
			),
		));

		// register moderate settings
		ap_register_option_group('moderate', __( 'Moderate', 'platformpress' ) , array(
			array(
				'name' => 'platformpress_opt[new_question_status]',
				'label' => __( 'Status of new question', 'platformpress' ),
				'desc' => __( 'Set post status of new question.', 'platformpress' ),
				'type' => 'select',
				'value' => $settings['new_question_status'],
				'options' => array(
					'publish' => __( 'Publish', 'platformpress' ),
					'moderate' => __( 'Moderate', 'profile', 'platformpress' ),
				),
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[edit_question_status]',
				'label' => __( 'Status of edited question', 'platformpress' ),
				'desc' => __( 'Set post status of edited question.', 'platformpress' ),
				'type' => 'select',
				'value' => $settings['edit_question_status'],
				'options' => array(
					'publish' => __( 'Publish', 'platformpress' ),
					'moderate' => __( 'Moderate', 'profile', 'platformpress' ),
				),
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[new_answer_status]',
				'label' => __( 'Status of new answer', 'platformpress' ),
				'desc' => __( 'Set post status of new answer.', 'platformpress' ),
				'type' => 'select',
				'value' => $settings['new_answer_status'],
				'options' => array(
					'publish' => __( 'Publish', 'platformpress' ),
					'moderate' => __( 'Moderate', 'profile', 'platformpress' ),
				),
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[edit_answer_status]',
				'label' => __( 'Status of edited answer', 'platformpress' ),
				'desc' => __( 'Set post status of edited answer.', 'platformpress' ),
				'type' => 'select',
				'value' => $settings['edit_answer_status'],
				'options' => array(
					'publish' => __( 'Publish', 'platformpress' ),
					'moderate' => __( 'Moderate', 'profile', 'platformpress' ),
				),
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[anonymous_post_status]',
				'label' => __( 'Status of anonymous post', 'platformpress' ),
				'desc' => __( 'Set post status post submitted by anonymous user.', 'platformpress' ),
				'type' => 'select',
				'value' => $settings['anonymous_post_status'],
				'options' => array(
					'publish' => __( 'Publish', 'platformpress' ),
					'moderate' => __( 'Moderate', 'profile', 'platformpress' ),
				),
				'show_desc_tip' => false,
			) ,
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<span class="ap-form-separator">' . __( 'Bad Words', 'platformpress' ) . '</span>',
			),
			array(
				'name' => 'platformpress_opt[check_bad_words]',
				'label' => __( 'Check bad words', 'platformpress' ),
				'desc' => __( 'Enable this to check for bad words in posts and comments. You can find bad words here ', 'platformpress' ). '<a href="https://raw.githubusercontent.com/platformpress/platformpress/master/theme/default/badwords.txt">badwords.txt</a>',
				'type' => 'checkbox',
				'value' => $settings['check_bad_words'],
				'show_desc_tip' => false,
			),
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<span class="ap-form-separator">' . __( 'Akismet check', 'platformpress' ) . '</span>',
			) ,
			array(
				'name' => '__sep',
				'type' => 'custom',
				'html' => '<span class="ap-form-separator">' . __( 'reCaptacha', 'platformpress' ) . '</span>',
			) ,
			array(
				'name' => 'platformpress_opt[enable_recaptcha]',
				'label' => __( 'Enable reCaptcha', 'platformpress' ),
				'desc' => __( 'Use this for preventing spam posts.', 'platformpress' ),
				'type' => 'checkbox',
				'value' => $settings['enable_recaptcha'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[recaptcha_site_key]',
				'label' => __( 'Recaptcha site key', 'platformpress' ),
				'desc' => __( 'Enter your site key, if you dont have it get it from here https://www.google.com/recaptcha/admin', 'platformpress' ),
				'type' => 'text',
				'value' => $settings['recaptcha_site_key'],
				'show_desc_tip' => false,
			) ,
			array(
				'name' => 'platformpress_opt[recaptcha_secret_key]',
				'label' => __( 'Recaptcha secret key', 'platformpress' ),
				'desc' => __( 'Enter your secret key', 'platformpress' ),
				'type' => 'text',
				'value' => $settings['recaptcha_secret_key'],
				'show_desc_tip' => false,
			) ,

		));
		ap_register_option_group( 'roles', __( 'User roles', 'platformpress' ) , array( $this, 'permissions_page' ), false );
	}
	public function permissions_page() {
		include 'views/permissions.php';
	}
}
